### ISSUE TITLE
Dúvidas: imagem docker do Flaresolverr

### ISSUE THREAD

**Issue by odouglsantos** [andreroggeri/pynuinvest#2]
E ai cara! Blz?

Tentei rodar seu projeto utilizando uma imagem nativa do Flaresolverr, porém não funcionou. A única que funcionou foi a sua hospedada no Docker Hub (achei bem por acaso, confesso).

Gostaria de entender contigo quais alterações você fez na sua imagem, se puder explicar ficarei muito agradecido.

Abs!

**Comment by andreroggeri** [comment]
Rapaz, excelente pergunta 😅 

Eu não me lembro exatamente, mas o que me vem na memória é que tinha um laço de repetição que executava só uma vez, e a correção foi rodar o laço até encontrar os valores. Mas não tenho mais o código aqui pra te responder com certeza 😢

**Comment by odouglsantos** [comment]
Tranquilo! vou tentar recuperar fuçando na imagem, levei um tempo pra descobrir porque não funcionava hahaha

Obrigado pelo retorno!
